export const environment = {
  production: true,
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYTIyNzRmYi1lZTE5LTQ1MTUtYTE1ZC01YmFjYWZjZTExMDkiLCJleHAiOjI1MzQwMjI3MjAwMCwiaXNzIjoiSEhEaXNjdXNzIiwiYXVkIjoiSEhEaXNjdXNzIn0.7B1GORFkva_G6_si7UpiNUs4yaDophslZvH1QzbBe4M'
};
